spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      ssl:
        enabled: true
server:
  ssl:
    key-store: ${KEY_STORE_PATH}/keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}